cloudant-labs/cloudant-follow

CHANGES.md
lib/feed.js
test/couch.js
test/follow.js
test/issues.js

See https://github.com/cloudant/nodejs-cloudant/issues/135 for more details.

Retry change request on last_seq

---

.eslintignore
.eslintrc.json
api.js
cli.js
lib/feed.js
lib/index.js
lib/stream.js
package.json

Add eslint

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
DCO1.1.txt

Add contributing documentation.

Add contributing documentation

---

README.md
lib/feed.js

Add view filter

---

.npmignore
CHANGES.md
Jenkinsfile
package.json

Run tests on Jenkins. Includes both QA and publish stages.
Add Jenkinsfile.

Run tests on jenkins

---

CHANGES.md
README.md
package.json

Prepare 0.14.0 release

---

CHANGES.md
lib/feed.js
test/params.js

Update list of possible feed query parameters.
Fixes #13.

Update list of possible feed query parameters

---

CHANGES.md
package.json

Prepare version 0.15.0 release.

Prepare version 0.15.0 release

---

CHANGES.md
package.json

Use latest request 2.x.x version.

Use latest request 2.x.x version

---

CHANGES.md
package.json

Prepare version 0.16.0 release.

Prepare version 0.16.0 release

---

CHANGES.md
package.json

Fixed `eslint` dependencies.
Corrected listing of `eslint` dependencies to `devDependencies`.
No new tests; packaging change.
Fixes #20

Corrected eslint to devDependencies

---

CHANGES.md
package.json

Prepared 0.16.1 release.
Incremented version number in `package.json` and `CHANGES.md`.
N/A
N/A

Prepared for 0.16.1 release

---

CHANGES.md
Jenkinsfile
lib/feed.js
package.json
test/unreliable_feed_test/mocks/mock_server.js
test/unreliable_feed_test/unreliable_feed.js

Retry '/_db_updates' request using `since` parameter.
Includes additional tests that use a mocked unreliable feed.
Fixes #23.

23 retry db updates with since

---

CHANGES.md
README.md
lib/feed.js
test/follow.js

Allow a custom HTTP agent to be specified.
Add new `httpAgent` key to feed configuration.
Includes additional unit test. Also tested externally using nodejs-cloudant client as custom HTTP agent.
Fixes https://github.com/cloudant/nodejs-cloudant/issues/98.

Use custom http agent

---

CHANGES.md
Jenkinsfile
lib/feed.js
test/follow.js

Remove '/_changes' endpoint from database URL.
Includes additional unit test.

Remove '/_changes' endpoint from database URL

---

package.json

chore: pin eslint to 4.15.0

---

.travis.yml
CHANGES.md
Jenkinsfile
lib/feed.js
package.json
test/couch.js
test/follow.js
test/issues.js
test/stream.js

- Fix Jenkins tests by getting the docker sidecar run to default to docker-in-docker.
- Make unit tests compatible with CouchDB 2.X.
- Remove redundant `agentRemove` socket call (fixes issue in Node.js v9.8.0).
- Run Jenkins tests against Couchdb versions "1.7.1" and "latest".
- Update engines in preparation for Node.js 4 EOL
| Node.js Version  | CouchDB@1.7.1 | Latest CouchDB@<i></i>2.X.X  |
| -----------------|:-------------:| --------------:|
| 6                           |<img src="https://travis-ci.com/images/logos/TravisCI-Mascot-1.png" width="50" height="50">||
| 8                           |<img src="https://travis-ci.com/images/logos/TravisCI-Mascot-1.png" width="50" height="50">||
| _latest_ …

Run jenkins test on couchdb2.x

---

Jenkinsfile

Wait for CouchDB to start when running Jenkins tests.

Wait for CouchDB to start when running Jenkins tests

---

CHANGES.md
lib/feed.js
test/issues/cloudant-follow/53.js

Correctly pass request parameters to feed filter function.
Includes additional unit tests.
Fixes #54.

Correctly pass request parameters to feed filter function

---

CHANGES.md
lib/feed.js

Abort request retry for dead feed.

Abort request retry for dead feed

---

Jenkinsfile

Added `gitTagAndPublish` to `Jenkinsfile`.
Replaced custom code with call to common `gitTagAndPublish` target.
Used common version parsing to identify release version for NPM publish.
- "No change"
- "No change"
- N/A build or packaging only changes
Note that the release tagging was tested with nodejs-cloudant and this is a code copy from there.
- "No change"

Added gitTagAndPublish to Jenkinsfile

---

.travis.yml

Changed Travis to use `npm install` for compatibility with `package-lock`.
Fixes #78 
Travis uses `npm ci` by default, which does not update the `package-lock` file. Changed the `install` step to explicitly use `npm install`:
```yaml
install: npm install
```
- "No change"
- "No change"
- N/A build or packaging only changes
- "No change"

Changed to npm install in travis

---

CHANGES.md
lib/feed.js
package-lock.json
package.json
test/issues/cloudant-follow/83.js

Support using `since="now"` parameter in a `/_db_updates` feed.
Fixes #83.
Skip `since` parameter validation if `/_db_updates` feed.
None.
None.
Additional unit test.
None.

Support using `since="now"` parameter in a `/_db_updates` feed.

---

CHANGES.md
package-lock.json
package.json

Prepare version `0.18.0` release.
Also, ran `npm audit fix` to update package files.

Prepare version 0.18.0 release

---

package-lock.json
package.json

Updated tap dependency to `^14.1.1`
Updated tap dependency to `^14.1.1`
- "No change"
- "No change"
- N/A build or packaging only changes
- "No change"

Greenkeeper/tap 14.1.1

---

.eslintrc.json
package-lock.json
package.json

Greenkeeper/eslint config standard 14.1.0

---

.travis.yml
Jenkinsfile

Greenkeeper is retired by now.
I removed a method call that would have called when we are on a greenkeeper branch.

Remove gkLockfile from Jenkinsfile
